### PR TITLE
Batching requests when querying Azure API

### PR DESCRIPTION
**Pull request by rolandvarga**
This change has been opened in response to issue #19

In order to improve the latency of the exporter I took the original approach from above issue and created a change.
This approach uses the batch endpoint just like Azure Portal. All configured resources are organized into batches and queried one call per batch.

### CODE REVIEW

**Comment by rolandvarga** [comment]
To show the improvement I have done some diagnosis on both the current implementation and the proposed change.

1. **Current master version**

| start_timestamp     | version_hash | #resources | duration      | 
|---------------------|--------------|-----------|---------------| 
| 2019-07-22 22:14:51 | 4411b47      | 11        | 4.245014099s  | 
| 2019-07-22 22:15:26 | 4411b47      | 11        | 10.822517785s | 
| 2019-07-22 22:16:06 | 4411b47      | 11        | 4.124153245s  | 
| 2019-07-22 22:16:41 | 4411b47      | 11        | 4.010924737s  | 
| 2019-07-22 22:17:15 | 4411b47      | 11        | 5.817058041s  | 
| 2019-07-22 22:17:50 | 4411b47      | 11        | 4.324651232s  | 
| 2019-07-22 22:18:25 | 4411b47      | 11        | 5.817686732s  | 
| 2019-07-22 22:19:01 | 4411b47      | 11        | 4.073717255s  | 
| 2019-07-22 22:19:35 | 4411b47      | 11        | 6.351667459s  | 
| 2019-07-22 22:20:11 | 4411b47      | 11        | 5.814142363s  | 
| 2019-07-22 22:20:47 | 4411b47      | 11        | 3.817252735s  | 
| 2019-07-22 22:21:21 | 4411b47      | 11        | 6.228149988s  | 
| 2019-07-22 22:21:57 | 4411b47      | 11        | 4.101702926s  | 
| 2019-07-22 22:22:31 | 4411b47      | 11        | 4.593554937s  | 
| 2019-07-22 22:23:06 | 4411b47      | 11        | 5.450421815s  | 
| 2019-07-22 22:23:41 | 4411b47      | 11        | 3.99987717s   | 
| 2019-07-22 22:24:15 | 4411b47      | 11        | 6.930276887s  | 
| 2019-07-22 22:24:52 | 4411b47      | 11        | 30.502321693s | 
| 2019-07-22 22:25:53 | 4411b47      | 11        | 4.028581229s  | 
| 2019-07-22 22:26:27 | 4411b47      | 11        | 5.211227803s  | 
| 2019-07-22 22:27:02 | 4411b47      | 11        | 5.381086328s  | 

2. **Proposed change**

| start_timestamp     | version_hash | resources | duration      | 
|---------------------|--------------|-----------|---------------| 
| 2019-07-22 20:04:25 | 2af295b      | 11        | 727.876739ms  | 
| 2019-07-22 20:04:56 | 2af295b      | 11        | 612.535351ms  | 
| 2019-07-22 20:05:27 | 2af295b      | 11        | 1.405562264s  | 
| 2019-07-22 20:05:58 | 2af295b      | 11        | 353.503774ms  | 
| 2019-07-22 20:06:29 | 2af295b      | 11        | 2.766641731s  | 
| 2019-07-22 20:07:02 | 2af295b      | 11        | 3.909671051s  | 
| 2019-07-22 20:07:36 | 2af295b      | 11        | 1.035120887s  | 
| 2019-07-22 20:08:07 | 2af295b      | 11        | 19.090556351s | 
| 2019-07-22 20:08:56 | 2af295b      | 11        | 492.987013ms  | 
| 2019-07-22 20:09:27 | 2af295b      | 11        | 4.609816091s  | 
| 2019-07-22 20:10:01 | 2af295b      | 11        | 399.870117ms  | 
| 2019-07-22 20:10:32 | 2af295b      | 11        | 613.289815ms  | 
| 2019-07-22 20:11:03 | 2af295b      | 11        | 537.366504ms  | 
| 2019-07-22 20:11:33 | 2af295b      | 11        | 782.963086ms  | 
| 2019-07-22 20:12:04 | 2af295b      | 11        | 1.06714814s   | 
| 2019-07-22 20:12:35 | 2af295b      | 11        | 930.195426ms  | 
| 2019-07-22 20:13:06 | 2af295b      | 11        | 937.317041ms  | 
| 2019-07-22 20:13:37 | 2af295b      | 11        | 630.635711ms  | 
| 2019-07-22 20:14:08 | 2af295b      | 11        | 1.235908078s  | 
| 2019-07-22 20:14:39 | 2af295b      | 11        | 521.310125ms  | 
| 2019-07-22 20:15:10 | 2af295b      | 11        | 850.689057ms  | 
| 2019-07-22 20:15:41 | 2af295b      | 11        | 715.787995ms  |

**Comment by brian-brazil** [comment]
That looks okay, are there any functions no longer in use that can be removed?

**Comment by brian-brazil** [comment]
Also, does this work out better in terms of request quota or is it the same? If this could be used to improve Azure SD quota issues over in Prometheus that'd be great.

**Comment by rolandvarga** [comment]
> That looks okay, are there any functions no longer in use that can be removed?

there was one `getMetricValue()` which I have just removed.

> Also, does this work out better in terms of request quota or is it the same? If this could be used to improve Azure SD quota issues over in Prometheus that'd be great.

@brian-brazil I hope I understood your question right. The headers are named slightly differently depending on the endpoint, but their value is decreased by 1 per request regardless of the number of resources sent:

**batch requests:**
```
./azure_metrics_exporter
2019/07/23 10:27:55 azure_metrics_exporter listening on port :9276
2019/07/23 10:27:57 X-Ms-Ratelimit-Remaining-Tenant-Reads => [11999]
2019/07/23 10:28:00 X-Ms-Ratelimit-Remaining-Tenant-Reads => [11997]
2019/07/23 10:28:00 X-Ms-Ratelimit-Remaining-Tenant-Reads => [11997]
2019/07/23 10:28:02 X-Ms-Ratelimit-Remaining-Tenant-Reads => [11996]
2019/07/23 10:28:05 X-Ms-Ratelimit-Remaining-Tenant-Reads => [11995]
2019/07/23 10:28:07 X-Ms-Ratelimit-Remaining-Tenant-Reads => [11994]
2019/07/23 10:28:10 X-Ms-Ratelimit-Remaining-Tenant-Reads => [11993]
2019/07/23 10:28:12 X-Ms-Ratelimit-Remaining-Tenant-Reads => [11992]
2019/07/23 10:28:14 X-Ms-Ratelimit-Remaining-Tenant-Reads => [11991]
```
**current master:**
```
./azure_metrics_exporter
2019/07/23 10:36:03 azure_metrics_exporter listening on port :9276
2019/07/23 10:36:05 X-Ms-Ratelimit-Remaining-Subscription-Reads => [11990]
2019/07/23 10:36:06 X-Ms-Ratelimit-Remaining-Subscription-Reads => [11989]
2019/07/23 10:36:06 X-Ms-Ratelimit-Remaining-Subscription-Reads => [11988]
2019/07/23 10:36:07 X-Ms-Ratelimit-Remaining-Subscription-Reads => [11987]
2019/07/23 10:36:07 X-Ms-Ratelimit-Remaining-Subscription-Reads => [11986]
2019/07/23 10:36:07 X-Ms-Ratelimit-Remaining-Subscription-Reads => [11985]
2019/07/23 10:36:07 X-Ms-Ratelimit-Remaining-Subscription-Reads => [11984]
2019/07/23 10:36:08 X-Ms-Ratelimit-Remaining-Subscription-Reads => [11982]
2019/07/23 10:36:09 X-Ms-Ratelimit-Remaining-Subscription-Reads => [11980]
2019/07/23 10:36:11 X-Ms-Ratelimit-Remaining-Subscription-Reads => [11979]
```

To me it looks like a small workaround the rate limit.

**Comment by rolandvarga** [comment]
Hi @brian-brazil! I have removed the unused code and this PR is ready for reviewal.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
