### PR TITLE
Transition to using dep for dependencies

### PR DESCRIPTION
**Pull request by hdost**

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. Prometheus is currently experimenting with dep, I'd prefer that to complete before switching away from what is the current standard.

**Comment by hdost** [comment]
@brian-brazil what do you typically do when you're not using dep to accomplish adding a new dependency for this repo? do you just download it and copy?

**Comment by brian-brazil** [comment]
Govendor is the current standard.

**Comment by VoyTechnology** [comment]
Should this be updated to use Go Modules instead?

**Comment by brian-brazil** [comment]
Yeah, Go modules is the done thing now.

**Pull request closed without merging**
